configure.ac
m4/lnav_common.m4
m4/lnav_with_jemalloc.m4
m4/lnav_with_yajl.m4
src/Makefile.am

This should take care of the build related stuff required for compiling with the local yajl installed on the system. However, it seems like you have an extra method 'yajl_reset' added to the yajl codebase which is not in the upstream yajl codebase. The code will still have to be refactored to successfully compile against the local copy.

Partial fix for issue#53 (Allow the use of yajl installed on the system)

---

m4/lnav_with_readline.m4

On FreeBSD variants, readline functionality is provided by editline which
is almost compatible but not quite. We could do a specific check for
editline but if editline adds the functionality in the future, this
check will still continue to fail. Instead look for one of the symbols
currently missing in editline as a sanity check.

[build] Make sure readline has the necessary symbols.

---

m4/lnav_with_readline.m4

Do a standard check for libreadline and use '-lreadline' as usual.

Remove the check for libreadline.a

---

src/log_format.cc

The function is not really used anywhere and does not really do what the
name suggests it should. It leads to compiler warnings about 'unused'
function. Removing this for now.

Remove unused 'strncasestr_i'.

---

src/environ_vtab.cc
src/readline_curses.cc

Minor changes to stop Coverity from complaining. I am not sure what is the correct way to initialize an array in C++11 and whether we actually care.

Minor changes.

---

src/environ_vtab.cc

There is a possibility that 'name' might be NULL and {get/set}env might
dereference it.

[Coverity] Eliminate null pointer dereferencing.

---

configure
configure.ac
src/config.h.in

* On some misconfigured systems, libgpm is required along with ncurses.
I haven't been able to figure out the correct way to figure out these
dependencies without resorting to using external tools like 'nm'. So
for the moment, if libgpm is not found, at least warn the user that
the build might fail later.
* Ncurses on OS X does not require libgpm, so there is no need to test
for it.
* There seems to be an 'AC_DEFINE' _BSD_SOURCE which does not seem to be
used anywhere. Removing this for now.
* Remove some artifacts left behind by Emacs.

[build] Warn if libgpm is missing and other minor changes.

---

src/pretty_printer.hh
test/datafile_xml.0

With the recent change to enable pretty print on all the log lines in
the current view, 'lnav' adds extra new lines between all the normal log
lines. This change removes the extra new lines.
__Not really sure if this is the correct fix or not but running various logs through lnav after this change seems to work fine.__

[pretty print] Avoid extra new lines.

---

.travis.yml

I think if `make check` fails, the `&&` will short out and will not print the logs
when it is most useful. Print out the log as an 'after_script'.
__Going on a hunch here. Will see what travis does during pull request.__

[travis] Print out the logs after failure.

---

configure.ac
m4/ax_with_curses.m4
m4/lnav_with_jemalloc.m4
m4/lnav_with_readline.m4
m4/lnav_with_sqlite3.m4
m4/lnav_with_yajl.m4

* Remove some of the obsolete macros.
* Use AC_CONFIG_MACRO_DIR to allow compatibility with older versions of
autoconf.
* Remove AU_ALIAS from curses macro.

[build] Get rid of warnings from autoreconf.

---

.travis.yml
test/test_logfile.sh

Something seems to have changed in the travis infrastructure. It has
suddenly started complaining about 'test' usage in test_logfile.sh and
not printing out the test logs after the run.

[travis] Fix travis behavior.

---

test/scripty.cc

Seems like timeval is defined differently on OS X than on Linux. So
fixing the format specifier on one breaks it on the other. Explicitly
cast the value being passed in to fix the problem on both the platforms.

[-Wformat] Fix scripty.cc again.

---

src/Makefile.am

Can't turn on the same on tests because it breaks on some test cases.

[build] Turn 'sign-compare' in to an error.

---

m4/lnav_with_sqlite3.m4

The AutoMake scripts honor the SQLITE3_XXX flags already. There is no need to
keep adding stuff to the environment variables.

[build] Stop adding to the environment variables.

---

src/readline_curses.cc

[terminal] Print out an error when openpty fails.

---

src/Makefile.am
src/pretty_printer.hh
src/timer.cc
src/timer.hh

Reverse lookup for pretty print should be a best effort undertaking. So,
+ Give up on EAI_AGAIN.
+ Don't block on the getnameinfo call indefinitely, resolv.conf might be
set up with a large timeout.
+ Disable lookups after the first failure.

[pretty] Don't wait indefinitely for reverse IP lookups.

---

configure.ac

'sqlite3_prepare_v2' was first introduced in version 3.3.9, which is
about 8 years old by now.

[build] Require sqlite3 to be at least version 3.3.9.

---

configure.ac

v3.6.0 was the last released version of sqlite3 that I could
successfully compile with without any source changes. I could
compile with v3.4.2 but that required some code changes and lnav
crashed regularly after that.

Require sqlite3-v3.6.0

---

src/default-log-formats.json

Not sure why, but v0.7.3 of lnav can't seem to recognize Auto Deploy's log format.

[format] Add a format for Auto Deploy.

---

src/listview_curses.cc

Hi there!
I found myself wanting a smaller horizontal movement than the half screen width currently implemented.  So I added shift-left and shift right along with H and L to shift the window by ten characters.
I think I've got the directions correct - right shifts the screen left and left shifts the screen right, similar to how left and right and h and l work.
Hope this helps,
Paul

Adding smaller movements to left and right via shift-arrows or H and L.

---

src/log_format.cc

I don't think there is any reason to capture the (OR) sub-group in
ERR(OR) separately.

[log_format] Don't capture the sub-groups.

---

src/default-log-formats.json

While looking through syslog messages on OS X, came across plenty of
error/warning messages where the level was in all-caps and as a result
were not recognized. There was also a lot of false positives due to the
word error turning up as part of a longer string.
This change:
- Changes the log level regex to do a case-insensitive search.
- Ognores the string 'error', if it is part of a longer string.

[syslog_log] Case-insensitive search for level strings

---

src/lnav.cc

'escape_index' is ensured to be less than 'sizeof(escape_buffer)-1'.
This guarantees enough space for one more character in the
escape_buffer. However, if we meet this condition, we go ahead and shove
a character and a null-terminator in to the string, potentially leading
to a buffer overrun.

[coverity] Avoid a buffer-overrun.

---

m4/libcurl.m4

This fixes tstack/lnav#253
The libcurl.m4 macros will still continue to look for a static archive
for libcurl but if one is not found and the binary is being compiled on
OS X, they will pick up the dynamic library if one is available.

[cURL] Allow libcurl to be dynamically linked in on OS X.

---

configure.ac

Use the autoconf macros instead of shell constructs.

[Autoconf] Minor cleanup.

---

m4/lnav_with_sqlite3.m4
src/lnav.cc
src/sql_util.cc
src/sql_util.hh
test/test_sql.sh

Prevent the users from attaching an external db file which they may not
have ownership of.
The current authorizer method is hooked in only when the LNAVSECURE
variable is set. This is done deliberately, since the method will be
called on every sqlite query and I did not want to incur a performance
hit.
If the scope of this authorizer increases, we should consider passing in
the lnav_data as pUserData and do the checks inside the authorizer
itself.

[secure-mode] Prevent users from attaching db files.

---

m4/lnav_with_sqlite3.m4
src/sql_util.cc
test/test_sql.sh

The code to handle in-memory db exceptions is hideous and unreliable,
given the fact that SQLite does not expose much in terms of getting the
current value and the methods to check the compile time options can
themselves be disabled by a compile=time option in SQLite.
There really isn't much use for in-memory databases and if someone
really needs it, they can always choose to run in normal mode, so just
remove the extra code.

[secure-mode] Disallow ATTACH statements completely.

---

README.md
appveyor.yml

This should resolve (at least with Cygwin) the issue https://github.com/tstack/lnav/issues/204
Please note that you will need to create an AppVeyor account, import your tstack/lnav project and then edit the README.md links accordingly.

Add cygwin continuous integration through appveyor

---

src/default-log-formats.json
test/logfile_glog.0

The log format used by glog uses spaces to left-pad the thread to 7 digits, [per the code](https://github.com/golang/glog/blob/65d6746/glog.go#L577):
```go
buf.nDigits(7, 22, pid, ' ') // TODO: should be TID
```
This fixes the regular expression to correctly match the extra whitespace.

[fmt] Fix glog_log format

---

release/vagrant-static/build.sh
release/vagrant-static/provision.sh

The default gcc toolchain on freebsd has been bumped to 4.8 so the build
scripts that hardcoded the gcc binary name are getting confused.
The new version of SQLite seems to be getting confused between editline
and readline.

[freebsd] Partial fix for the release builds.

---

docs/source/hotkeys.rst

This is mentioned in the lnav 0.6.2 release notes:
http://lnav.org/blog/2013/11/10/word-wrap-support-in-v062
But doesn't appear to be mentioned elsewhere.

Add Ctrl-W display shortcut for word-wrap.

---

src/help.txt

I found it too hard to quickly locate keybindings within the built-in help text, and noticeably easier in the online manual.  This was simply due to the nice grouping of bindings into categories, so I roughly replicated that in the built-in help text.
Eventually it would be good if the built-in help and online manual had exactly the same information for this, generated from the same source.  It doesn't make much sense to me to duplicate the information in two slightly different ways, since that is error-prone and doubles the maintenance work.

Group keybindings in built-in help text

---

configure.ac

If we have both 64-bit and 32-bit versions of ncurses installed, currently the 32-bit libraries in `/lib` get found first, so `gcc` fails to link against them, and `./configure` ends up thinking that we're missing `ncurses` libraries.
So scan `/lib64` before `/lib`.  There might be a better fix, but hopefully it will avoid breaking 32-bit distributions and distributions which have 64-bit libraries in `/lib`.

fix compile on SUSE

---

src/hotkeys.cc

`o`/`O` do not move forward/backward an hour; in fact, no hotkey does, but `6`/`^` are about as close as it gets.

fix hints about moving by hour

---

src/Makefile.am

Since 26cd9f59 introduced stricter timestamp parsing so that the full string now has to be matched, several of the 3rd party formats installable via `lnav -i extra` broke.  So add a couple more very common timestamp formats to address these.

add two more common time formats

---

src/lnav.cc
src/lnav_commands.cc
src/lnav_log.cc
src/lnav_util.cc
src/log_format.hh
src/papertrail_proc.hh
src/ptimec.hh
src/relative_time.cc
src/url_loader.hh
src/yajlpp.hh

This fixes a large number of compiler warnings.  There are still quite a few left; almost all of the remaining ones could be fixed with a similar approach but I have already spent way more time on `lnav` than I should have this weekend.
**N.B. These should all be carefully sanity-checked, as I am really a C++ newbie.**

Fix compile warnings

---

src/logfile.cc

Resolves a crash on startup on FreeBSD/i386 - st_size is 8 bytes, treating it as an int without casting segfaults in log_msg()'s vsnprintf() call.
Cast to long long and fix the format string to match to avoid truncation.  For completeness do the same with st_mtime.

[logfile] Fix format string in debug log.

---

docs/source/commands.rst
src/lnav_config.cc
src/lnav_config.hh
src/view_curses.cc

This is to address #270.  Based off @Ass-Pirate's [comment](https://github.com/tstack/lnav/issues/270#issuecomment-195779692) with further attempt to not break other color pairs such as status lines.
To enable:
```
:config /ui/default-colors true
:save-config
```
Restart lnav

add config option to use default fg/bg colors

---

docs/source/commands.rst
src/help.txt
src/lnav_commands.cc
test/expected_help.txt

Add a ':quit' command and add ':q' as the alias for the
quit command.
Closes #470

[command] Add a ':quit' command.

---

src/command_executor.cc
src/grep_proc.cc
src/lnav.cc
src/lnav_util.cc
src/lnav_util.hh
src/readline_callbacks.cc

* Remove all the wordexp related unused headers and code.
* On OpenBSD (maybe other BSDs too) stdout is defined as a macro that expands to
`&__sF[1]` and not `FILE *`. As a result an expression like `stdout = fdopen(...)`
becomes invalid, since the lvalue is not assignable. So instead of assigning a pointer,
change the value pointed to by `stdout` instead, which seems to work on OpenBSD
and at least on macOS. This might barf if the value pointed to by stdout is in the `readonly`
section but haven't found that to be the case so far.
* defining `_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_` seems to fix the const
correctness related redefinitions between `wchar.h` imported from
the system libc and the one imported by clang++ STL. Making sure that this only kicks
in when compiling with Clang and on …

Fix lnav builds on OpenBSD

---

src/command_executor.cc

Fixes warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

Fix comparison between signed and unsigned int

---

src/log_format.cc
src/pcrepp.hh

It should pass only the matched length, not the original string length.
Caught by -fsanitize=address while trying to parse "some string (DEBUG)"
Probably deserves a unit test.  I started one, but felt a little directionless.  Might try again later.

string2level uses wrong string length

---

docs/source/hotkeys.rst
src/filesystem/path.h
src/help.txt
src/hotkeys.cc
src/logfile.hh
src/logfile_sub_source.cc
src/logfile_sub_source.hh
test/expected_help.txt

Updates #372 
I removed the wholesale search-and-replace of `filename` with `basename`, mainly because it's a lot of noise to bring across so much time, and it's not necessary in the end.

Toggle filenames attribute fixes

---

src/grep_proc.cc
src/lnav.cc

I had some issues building 0.8.3 on gentoo with musl as libc (amd64).
First of all, CEOF is not defined. I'm guessing, that it is the same as EOF, but I couldn't figure out, where the CEOF comes from or what it should be.
Secondly FILE is an incomplete type on musl and in turn it can't be dereferenced. This is allowed by the standard and it is undefined/unspecified/implementation defined/whatever behavior to dereference a FILE*. The code in question looks a bit funky. I don't know, why the file descriptor for STDOUT is opened at this place and why you would reassign stdout. The may be some intention behind that, but from looking at the history, I couldn't figure it out.
You may want to check both of those changes, as I am not confident, that this won't break anything, as I don't know, why …

Fix some build issues with musl as libc

---

snapcraft.yaml

*Snap packages* is one of the new package format that runs on many Linux distributions and also developer boards like the Raspberry Pi. They provide confinement of the snapped package and work especially well with Ubuntu Core. Confinement is good, because if somehow the application is compromised from malformed logs, it will not affect the rest of the system.
This PR adds a file `snapcraft.yaml` at the root of the repository.
To create the snap package yourselves: 
1. Install snap support, if your Linux distro does not have it already (https://docs.snapcraft.io/core/install)
2. Install the *snapcraft* snap creation tool, with `sudo snap install snapcraft --classic`
3. In the `lnav` directory, run `snapcraft`. This will generate the snap package *lnav_0.8.3_amd64.snap*. (To clean up, run …

Added snap package support

---

src/sysclip.cc

The clip.exe command only supports writing. This is tested on WSL Ubuntu.

Support for Windows Subsystem for Linux clipboard command

---

src/default-log-formats.json

So ":set-min-log-level info" gets rid of lines with DEBUG.

Fix openstack_log debug level

---

example-scripts/clipboard.sh
src/sysclip.cc

I think config variables would be better than this ladder of hardcoded commands. People working on tmux under an xterm may prefer that the clipboard go to one or the other -- I use a wrapper script inspired by neovim. I guess if I had my way: if the config didn't specify a command, then a minimum of sensible defaults would be hardcoded, but this is an example of what works in practice. 
`command -v` is faster than `which`, and guaranteed on POSIX. 
Keep up the good work!

More clipboard commands

---

lnav.1

That -s parameter doesn't seem to be used anymore. It was even removed from the _usage_ examples in **lnav.cc**.

Fix typo in manpage

---

src/default-log-formats.json

Default `ErrorLogFormat` from Apache add a `tid` info (Thread ID) for some multithreaded configuration.
https://httpd.apache.org/docs/2.4/en/mod/core.html (see "default format for threaded MPMs" example)
This PR provides `tid` parsing if available.

Add thread id for multithreaded Apache error log

---

configure.ac

When building with non-root toolchains (gentoo-prefix for instance), it confuses the toolchain to use non-existing libraries.

Don't force system library path

---

AUTHORS
src/base/lnav_log.cc
src/formats/vmw_log.json
src/lnav_config.hh

- AUTHORS: Replace username with contributor's actual name.
- lnav_log.cc: Put the variable declaration behind the same macros as their usage.
- lnav_config.hh: Remove the unused sys/queue.h headers.
- vmw_log.json: Optimize the vum-log4cpp regex.

Minor changes to quell some compiler warnings and other miscellaneous changes.

---

release/Makefile
release/vagrant-static/Vagrantfile
release/vagrant-static/build.sh
release/vagrant-static/musl-pkg.sh
release/vagrant-static/provision.sh

`musl-package` release target compiles a completely static `lnav` binary compiled with
musl-libc.

[release] Build target for static lnav compiled with musl-libc.

---

src/Makefile.am

Some compilers automatically append the system binary suffix. If lnav is
cross compiled on such systems; then we should be using this suffix for
the binaries that are built and run as part of the build process.

[cross-compile] Use 'BUILD_EXEEXT' as the suffix for build binaries.

---

release/vagrant-static/Vagrantfile
src/base/lnav_log.cc

Posix basename apparently modifies it's arguments and lnav_log.cc calls
basename on static strings.

[freebsd] Remove basename from log_msg.cc and update the FreeBSD image in the VagrantFile.

---

src/Makefile.am
test/Makefile.am

This fixes the generated files from being packaged but breaks the `make
libdiag.a` implicit target but I haven't found a clean way of fixing
that yet.

[dist] Prevent distributing built sources

---

src/Makefile.am

Remove init-sql.h from the distributed package and remove the redundant
files from DISTCLEAN.

[dist] Some more distribution related cleanup.

---

src/line_buffer.cc
src/line_buffer.hh

Don't try to continue reading the next stream of a concatenated
gzip file.  The next stream may be CRC noise or other garbage.
Maybe in the future we should look for a gzip header in the
following bytes of the stream and try to decode from there.
But it's not clear that anyone ever uses this supposed gzip
feature anyway.
Let's just end the stream when we reach EOS. Also, if the
stream fails to init, let's leave it closed instead of throwing
an error no one is likely to catch.  Log the error msg from
zlib if one is provided.

Don't try to read concatenated gzip streams

---

release/vagrant-static/provision.sh

Recent terminfo databases contain two entries for tmux sessions,
`tmux` and `tmux-256color`. This change adds these two entries.
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

Add `tmux` terminfo entries

---

src/line_buffer.cc
src/line_buffer.hh

This reverts the previous fix and fixes the earlier crash in a different way (simply by not crashing on unexpected data).  gzip streams need better coddling, and this is enough for them, it seems.
This re-enables multi-part streams. Those are somewhat common.  I found some in my logs that I were being cut off early with my previous change.

gzip stream continuation

---

docs/source/formats.rst

The schema should be `format` instead of `config`.
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

Fix schema reference

---

docs/source/usage.rst

To avoid surprise, just mention the name of the remote binary file that is written and deleted immediately.
Sometimes it is not deleted. (when ?)

Mention the name of the remote binary file

---

.github/workflows/c-cpp.yml

Since lnav is now buildable for Windows, github actions come in handy to automate this process for a release.
Now I see the release is a bit outside github actions, but I think this PR might be a good start.
On by fork I have managed to automate the release as well, triggered by tagging and publish (for now) the windows zip.
@tstack do you think this is a good direction?

Proposal to add github actions to build for Windows

---

src/base/string_util.cc

Lnav fails to build on the next Fedora version due to the following error:
```
make[3]: Entering directory '/builddir/build/BUILD/lnav-0.10.1/src/base'
g++ -std=c++14 -DHAVE_CONFIG_H -I. -I../../src   -Wall -I../../src/ -I../../src/third-party -I../../src/fmtlib     -I../../src/third-party/doctest-root  -I/usr/local/include -D_ISOC99_SOURCE -D__STDC_LIMIT_MACROS -D_GNU_SOURCE  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o string_util.o string_util.cc
make[3]: Leaving …
```

Add `#include <iterator>` to `string_util.cc`

---

src/formats/formats.am
src/formats/unifi_log.json

This PR adds support for the UniFi gateway log format, which can be leveraged as follows:
```shell
ssh -fn gateway 'tail -fqn 1000 /var/log/messages' 2>/dev/null | lnav
```

Add format for UniFi gateway

---

src/formats/unifi_iptables_log.json
src/formats/unifi_log.json

This format allows the parsing of the new /var/log/iptables firewall log files for the [UniFi Dream Machine](https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-12-15/bc5658b5-3f40-43ea-bc23-cd2c28c228cc?page=11).

unifi: Support iptables log file

---

test/Makefile.am

I believe the test/remote folder only needs to be setup for
test/test_remote.sh. Prior to this commit, it was being built during
make, rather than just during make check. This commit adjusts things so
that the test/remote folder is only generated during make check, and
only when test/test_remote.sh is being executed.
Fixes #1040
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

Only build ssh keys when needed

---

src/view_curses.cc

Hello @tstack .
Elements of type VC_GRAPHIC used as column separators, when used along with background coloured bars to express numeric column values or in the presence of highlighted areas, maintain alternate-line reversing of colours when inside the bar range and take the foreground color/reversing state of the last coloured bar on the line even though when not placed within the coloured range of characters.
This commit fixes this.
Below some before/after pictures.
Before:
After:
Note: I've only tried this with the log and db views, so it would help if it could be tested with other views to be extra sure.

[view_curses] Fix for fg colour and reverse attribute for separator bars

---

src/formats/access_log.json

It seems most web servers log an empty referer as `"-"`, but GitLab's nginx actually logs an empty field instead (`""`). Allow this in the standard CLF format parser.

Handle empty referer in access log (fixes #1059)

---

src/CMakeLists.txt
src/time_formats.am

%H:%M:%S.%f should be useful for large log files where a log happens within a second

Add %H:%M:%S.%f format

---

m4/ax_check_pcre2.m4

This used to add -L/lib to LDFLAGS which was not an issue unless you are cross compiling and then it may detect PCRE features based on the host PCRE not the target one.

[pcre2] don't add PRCE2_HOME to the search path if it is empty

---

docs/04_tutorials.md

"in" was missing from a sentence.

Fix typo in the tutorial presentation page

---

src/base/lnav_log.hh

GCC 13 (as usual for new compiler releases) shuffles around some internal includes and so <cstdint> is no longer transitively included.
Explicitly include <cstdint> for uint32_t.
Signed-off-by: Sam James <sam@gentoo.org>

Fix build with GCC 13 (add missing <cstdint> include)

---

docs/source/formats.rst

- fixes https://github.com/tstack/lnav/issues/733
- add a reminder that formats can be loaded from `/etc/lnav/formats`

doc: provide an example of overriding only the error detection regexp for a format

---

.github/workflows/c-cpp.yml
.github/workflows/coverity.yml
.github/workflows/tailer-ape.yml

Bump `actions/checkout`, and `actions/upload-artifact` to `v3` (Node 16) from `v2` (Node 12) this fixes the Node 12 deprecation warning shown currently under Annotations in action runs.

CI (workflows): bump actions version, fix Node 12 deprecation warning in action runs

---

src/base/strnatcmp.c

The valid values to pass to `isdigit()` is the values represented by `unsigned char` and the value of EOF (usually -1).  Other values such as the other negative `signed char` values may invoke undefined behaviour.
Fix this by casting the argument to `isdigit()` to `unsigned char`.
Found by building on NetBSD/macppc with -Wchar-subscripts turned on.

strnatcmp.c: ensure correct value range for isdigit() argument.

---

src/third-party/ArenaAlloc/arenaallocimpl.h

Use the constants defined by <stdint.h> to avoid right-shift by 32 on a 32-bit host by comparing SIZE_MAX to UINT32_MAX, since `value` is a size_t.
Found by building on NetBSD/macppc with -Wshift-count-overflow (which is default on in the pkgsrc setup, which this is from).
./third-party/ArenaAlloc/arenaallocimpl.h:111:22: warning: right shift count >= width of type [-Wshift-count-overflow]
111 |       value |= value >> 32;
|                ~~~~~~^~~~~

ArenaAlloc/arenaallocimpl.h: avoid shift overflow on 32-bit hosts.

---

.github/workflows/bins.yml

This change adds support for creating statically linked arm (armv7l, aarch64) binaries in the CI jobs.
Re: #558

[build/arm] Add support for arm binary compilation in CI jobs.

---

docs/_posts/2018-04-05-linux-magazine-tutorial.md

The link to linuxmagazine is dead. Replacing it with the last archived link on the wayback machine.

[posts] Replace dead link with an archived link.

---

.github/actions/muslbuilder/Dockerfile

Cmake isn't used in the build script and make is installed on the container image using apk and doesn't need to be compiled from source.

[build] Remove unnecessary entries in the Dockerfile.

---

docs/source/formats.rst
src/base/string_util.cc
src/base/string_util.hh
src/log_format.cc
src/log_format_ext.hh
src/log_format_loader.cc

Another useful field shortening algorithm added: "last-word"
```json
"line-format": [
{
"field": "logger",
"overflow": "last-word",
"max-width": 30,
"min-width": 30,
"align": "right"
},
],
```
original log:
```log
2024-03-27 15:22:51.534 DEBUG com.example.digital.ms.excorporate.notification.business.services.implementation.CamelExecutor Get AccountDetailsDTO batchSize:10000, offset:0
2024-03-27 15:22:26.970 DEBUG com.example.digital.ms.excorporate.notification.couchbase.NotificationRepositorylistCorpUsageProcessor:: [QueryResultWithTotal{data=null, total=9}]
```
resulting log:
```log
2024-03-27T15:22:51.534 DEBUG                  CamelExecutor Get AccountDetailsDTO batchSize:10000, offset:0 
2024-03-27T15:22:26.970 DEBUG         NotificationRepository listCorpUsageProcessor:: …
```

last-word shortening algorithm added

---

src/vtab_module.hh

* GCC 15 is more aggressive about checking dependent names
Bug: https://bugs.gentoo.org/936409

[build] fix for GCC 15 two-phase lookup

---

src/formats/nextcloud_log.json

First of all, thanks a lot for lnav.
We at nextcloud have been using it for quite a while, but I never found the time to upstream the config we were using.
Since the update to Ubuntu 24.04 and therefor getting the "new lnav" (> 0.10) our old config did not work anymore and now I discovered you are shipping a nextcloud one already.
I don't know if there are "rules" for the logs, but I find it much easier with these small changes:
- level at the beginning, so it can be "navigated away", or skipped as the color helps already
- shorten IP (v6 is taking quite some space otherwise)
- consistent length of app id
- added exception class (with color identifier) and message
- added hint for data array
~~The other thing I couldn't figure out is how to get rid of the "always displayed" …

Simplify nextcloud_log format

---

src/third-party/prqlc-c/Cargo.lock
src/third-party/prqlc-c/Cargo.toml

* Bump 'prqlc' package to latest stable
* Deterministic build (as no `cargo build --locked` currently in `src/Makefile.am`) #1319
* Simplify further lnav versions gentoo ebuild generation (via `cargo ebuild`)
* Currently this PR patch will be used to build 0.12.2 (https://bugs.gentoo.org/938293)

[build] bump and use stable/locked 'prqlc' package version

---

src/lnav_config.cc

The destination can be either the `local_formats_path` or the `local_configs_path`.

Fix output of `lnav -i` to message the actual destination

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [LNAV Guru](https://gurubase.io/g/lnav) to Gurubase. LNAV Guru uses the data from this repo and data from the [docs](https://docs.lnav.org) to answer questions by leveraging the LLM.
In this PR, I showcased the "LNAV Guru", which highlights that LNAV now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable LNAV …

Introducing LNAV Guru on Gurubase.io

---

docs/schemas/config-v1.schema.json
docs/source/config.rst

This is my suggestion on how to improve the demux docs.
I did change the structure of the page though. If you don't like that I can revert it!
I was initially very confused that directly below the "Demux" section I get the reference for watch expressions which is why I moved the reference directly underneath each section.
/fixes https://github.com/tstack/lnav/issues/1355

Expand demultiplex documentation

---

configure.ac
src/Makefile.am

tested by building natively on x86_64 and cross from x86_64 to armv8 and armv7.

fix cross compilation in rust-related Makefile parts

---

configure.ac
src/Makefile.am

fixes for the darwin issue in https://github.com/tstack/lnav/pull/1360#issuecomment-2564395405
I don't have access to darwin, tested by `autoreconf -fv && ./configure --host x86_64-apple-darwin22.6.0 CC=cc`
for the musl issue the error message is quite clear: to cross compile rust to musl you need the corresponding toolchain. How did it even work before?

Fix cross rust2

---

src/third-party/rapidyaml/ryml_all.hpp

Hi maintainers,
Compiling the lnav failed for loong64 in the Debian Package Auto-Building environment.
The error log is as follows,
```
In file included from yaml-extension-functions.cc:36:
./third-party/rapidyaml/ryml_all.hpp:514:5: error: #error "unknown CPU architecture"
514 |    #error "unknown CPU architecture"
|     ^~~~~
g++ -std=c++17 -DHAVE_CONFIG_H -I. ......
```
The full build log can be found at https://buildd.debian.org/status/logs.php?pkg=lnav&ver=0.12.3-1&arch=loong64.
Please review this commit.
Based on this commit, lnav 0.12.3-1 source package was built successfully on locally.
```
Testsuite summary for lnav 0.12.3
=====================================
=====================================
......
dh_builddeb
dpkg-deb: building package 'lnav-dbgsym' in …
```

Add loongarch64 support

---

docs/source/sqlext.rst

Currently this is sort of implied in the documentation, since only a few fields are mentioned as being updateable.
This makes it a bit clearer.

Add a note clarifying that builtin fields in sqlite tables are read-only, unless otherwise mentioned.

---

src/yaml-extension-functions.cc

Without this change, yaml_to_json failed on my machine with this error:
error: SQL statement failed
reason: misuse of sqlite3_result_subtype() by yaml_to_json()
And this results in dirty src/internals/sql-ref.rst after "make" every time.

register SQLITE_RESULT_SUBTYPE property for yaml_to_json

---

src/yajl/yajl_tree.c

**Description**
This PR fixes a potential vulnerability in yajl_tree_parse() that was cloned from yaml but did not receive the security patch. The original issue was reported and fixed under https://github.com/likema/yajl/commit/31531a6e6b5641398237ce15b7e62da02d975fc6.
This PR applies the same patch to eliminate the vulnerability.
References
https://nvd.nist.gov/vuln/detail/CVE-2023-33460
https://github.com/likema/yajl/commit/31531a6e6b5641398237ce15b7e62da02d975fc6

Fix for CVE-2023-33460: Memory leak in yajl 2.1.0 with use of yajl_tree_parse function

---

snapcraft.yaml

So that other snaps, e.g., the `juju-lnav` snap [1], can use the `lnav` binary.
[1] https://github.com/nicolasbock/juju-lnav/blob/main/snap/snapcraft.yaml#L36

Add content interface to snap

---

src/listview_curses.cc

Hi, this fixes an issue with jumping over very long lines (that don't even fit on screen) (btw this's a common case in our logs) with "Page Up".
In such cases `rows_available` returns 1 and `shift_amount` evaluates to 0, meaning you can't progress towards the top. In the fix I ensured that `rows_available` has enough value to proceed, which is close to what has been done in "Page Down" code.
Note #1: I used this script to generate a text file to test on:
```
with open("test-big.log", "w") as f:
f.writelines(f"before {i}\n" for i in range(1, 81))
f.writelines(f"{i} ThisIsALongLine, " for i in range(1, 1500))
f.write("\n")
f.writelines(f"after {i}\n" for i in range(1, 81))
```

[listview] fix jumping over very long lines with Page Up
