tstack/lnav

- src/log_format.cc
- src/log_format.hh
- src/log_format_impls.cc
- src/test_override.cc
- test/drive_vt52_curses.cc
Some minor code changes to get rid of clang warnings and some compilation errors when building with older compilers.
__Actual code changes. Would like them reviewed before merging them.__
> Code changes to get rid of warnings & errors.

- configure
- configure.ac
- src/config.h.in
....and note to self: "RTFM next time".
> Let BSD definitions take precedence.

- src/Makefile.am
- src/Makefile.in
- test/Makefile.am
- test/Makefile.in
Add custom silent rules for ptime/bin2c/sqlite3/rm commands.
> [build] Add custom silent rules.

- .travis.yml
Creating a pull request to enable coverity scan. Hopefully, it will kick in during pull request validation and I can close this off without merging.
> Enable Coverity scan.

- .travis.yml
This reverts commit 7898d4d0d5797cf0522a791670000f6b7b036ca4.
> Revert "Enable Coverity scan."

- src/Makefile.in
Added a new time format to the list
> [time_formats] Added another time format

- configure.ac
- src/lnav.cc
- src/lnav_log.cc
__Something I've been playing around with. Maybe not useful.__
> [build] Add the git cln to the lnav version.

- test/test_sql.sh
* Test for attaching db when passed in through as a command line
argument.
* Test for attaching db from within lnav.
> [test] Add tests for attaching to sqlite3 db.

- NEWS
- docs/source/hotkeys.rst
- src/help.txt
- src/lnav.cc
* Change the 'lo-fi' shortcut to 'Ctrl-l'
* Remove the shortcut for 'redraw'
> [lo-fi shortcut] Change shortcut to 'Ctrl-l'.

- release/vagrant-static/provision.sh
> [release-builds] Fix the FreeBSD builds.

- docs/source/hotkeys.rst
If there was a way to view the current session, I'd include that as well, but I haven't dug deeply enough to work that out.
> Start a Sessions section in hotkeys documentation, mentioning Ctrl+R.

- src/default-log-formats.json
Added a new pattern to support the new log format which was introduced in 4.1 and updated the URL
> Update the Vdsm log configuration to support the Vdsm 4.1 log format

- README.md
> document usage with systemd-journald (#61)

- test/drive_shlexer.cc
> [test] Fix printf format specifier for size_t.

- src/Makefile.am
for day month year hour:minutes:seconds and optional milliseconds
day month year is an internationally used convention.
> Added used time formats

- src/readline_callbacks.cc
Replace mkstemp with std::tmpfile
TMPDIR is not always defined in the environment but the code doesn't check
for that. Let's used std::tmpfile instead.
Maybe an easier fix is to perform the tmpdir lookup better, but that is
also noisy since the search for a decent tmpdir is based on lore.
std::tmpfile() is rather clean. However it does not leave a nice filename
name around for debugging, so I understand why it might not be preferred.
Fixes #495
> Replace mkstemp with std::tmpfile

- README.md
> Added -a hint to journald usage.

- src/extension-functions.cc
Signed-off-by: Benny Zlotnik <uber442@gmail.com>
> Remove redundant the

- src/line_buffer.cc
- src/line_buffer.hh
- test/drive_line_buffer.cc
- test/test_line_buffer.sh
The gzread function is slow.  Every time you seek to a new location, the
whole file up to that position has to be decompressed again.  This causes
massive lags when trying to do simple things in lnav on a large .gz file.
Use the zlib inflate* functions instead and record the dictionary
periodically while processing the file the first time.  Then use
inflateSetDictionary to restore the dictionary to a convenient
location when trying to seek into the file again in the future.
Use a default period of 1MB of compressed data for syncpoints.
Each syncpoint uses 32KB. This is a ratio of 3.2%.  For example,
a 1GB .gz file (compressed size) will require us to keep 32MB
of index data in memory. A better method may be to use a fixed
number of syncpoints and divide the file appropriately. This
would …
> Add a gzip indexing class for faster gz navigation

- src/formats/openstack_log.json
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>
> Add format for OpenStack Keystone log files

- docs/source/cli.rst
- src/base/paths.cc
- src/base/paths.hh
- src/lnav.cc
- src/pcap_manager.cc
- src/shlex.cc
- src/string-extension-functions.cc
- src/tools/bin2c.c
- src/view_curses.cc
- src/yajlpp/json_ptr.cc
- test/drive_data_scanner.cc
I have prepared github actions flow waiting for building in windows/msys2. I have tested in another fork and it produces windows binaries. For now, waiting for this PR to go through.
https://github.com/thedataflows/lnav/blob/windows-build/.github/workflows/windows.yaml
Successful run: https://github.com/thedataflows/lnav/runs/5261481976?check_suite_focus=true
Also, I have managed to do automated release based on tag, however I think the release part should be added to the general release process, that seems to be a tad custom for the moment with lnav.
> Fixes for building on Windows

- src/formats/unifi_log.json
This PR fixes scenario when prefixes are not used, and adds support for some edge cases to the UniFi format.
> UniFi improvements

- docs/source/formats.rst
Indentation correction in the formats.rst file
> Indentation correction in formats.rst

- src/spookyhash/SpookyV2.cpp
- src/spookyhash/SpookyV2.h
Try and make SpookyHash endianness-agnostic using macros copied from: https://github.com/k0dai/spookyhash
> [Endianness] Make SpookyHash endianness-agnostic.

- src/text_anonymizer.cc
Otherwise the build fails at the type checking
> Make build work on FreeBSD

- test/Makefile.am
- test/drive_listview.cc
- test/listview_output_cursor.0
- test/listview_output_cursor.1
- test/listview_output_cursor.2
- test/listview_output_cursor.3
- test/listview_output_cursor.4
- test/listview_output_cursor.5
- test/listview_output_cursor.6
- test/test_listview.sh
Tests the behavior of the most basic movement commands / keyboard inputs.
Slightly extends the ability of the test driver to allow for such tests.
Relates to: #1088.
> Some test cases for listview behavior in cursor mode

- .github/actions/muslbuilder/Dockerfile
- .github/actions/muslbuilder/entrypoint.sh
Modify the docker file to allow creating arm containers for compiling arm binaries. Also fix the entrypoint.sh script to allow running the containers locally.
> [arm] Allow creating arm containers.

- configure.ac
- src/Makefile.am
> Revert "fix cross compilation in rust-related Makefile parts"

- docs/source/formats.rst
This should suffice to close issue #608 IMHO.
> Add a note to regex wrt multiline format detection

- src/scripts/com.vmware.btresolver.py
> [btresolver] Update the URL.

- configure.ac
- src/Makefile.am
> Revert "Fix cross rust2"
